### ISSUE TITLE
Visibility support.

### ISSUE THREAD

**Issue by frankdejonge** [dbu/flysystem-phpcr#2]
It seems like this adapter does not support visibility. There's a `NotSupportingVisibilityTrait` trait you can use which throws the expected exception when setVisibility is used.

**Comment by dbu** [comment]
is visibility something that should work both with folder and files, or files only? i think at least for files, i could actually store that information. what is visibility supposed to do? remove the files from the directory listing calls?

**Comment by frankdejonge** [comment]
@dbu it's file only.

**Comment by dbu** [comment]
@frankdejonge just to make sure i understand correctly: 

* setting visibility is only possible for files, not folders. 
* visibility is supposed to affect the listContents method by hiding files that are private
* (and if the underlying storage knows that concept, it would be reflected there - for phpcr this is not the case, but we can store any metadata along with the file, including this data)

**Comment by frankdejonge** [comment]
@dbu point 1 is correct. The visibility does not affect listContents, all files are listed. Storing metadata is possible through the api, by passing it in the Config, _but_ it's not the primary reason it's there. Metadata _can_ be retrieved through the getMetadata call and _may_ have that additional metadata.

Does that clear things up?

**Comment by dbu** [comment]
@frankdejonge thanks. almost there - the thing i still don't get is what visibility private has as effect. is that just something to write and read back, but has no effect on the adapter behaviour?

**Comment by frankdejonge** [comment]
@dbu this basically only affects direct access to the filesystem. For instance, when using a local filesystem (which can be the webroot) the file can be private to restrict it from being accessed over http. The same goes for S3 assets, which can be accessed over http too. By setting it to private, it's basically saying "don't access it in the fs directly".

**Comment by dbu** [comment]
@frankdejonge i feel slow (maybe still too much wurst) but: how would the local filesystem handle this information? i know about file ownership and the permissions for owner, group and all, but i would not know how to mark a file in the filesystem to not be read by apache/nginx/whatever.
is this something that the Filesystem class of flysystem is using or is it supposed to be a built-in feature of the underlying storage system?

**Comment by frankdejonge** [comment]
@dbu for the local filesystem it's basically a chmod, not a chown, which has the desired effect. Maybe we can turn this around. I'm not super familiar with phpcr... Is there a way to access the filesystem you're manipulating directly? Does it expose itself over http (without an API in between)? If not, visibility is not really something you have to be concerned with. If it does, is there a way to say "the public access is restricted or allowed" then this should be reflected in the adapter.

**Comment by dbu** [comment]
@frankdejonge okay, get it now i think. PHPCR itself is only an API, so no direct HTTP access to it. so i will add the trait as a solution. thanks!
